<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG0axxop\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG0axxop/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG0axxop.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG0axxop\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG0axxop\App_KernelDevDebugContainer([
    'container.build_hash' => 'G0axxop',
    'container.build_id' => 'b81dd8bc',
    'container.build_time' => 1601388245,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG0axxop');
